### ISSUE TITLE
Check if document_term_matrix is too large for a braodcast variable or not.

### ISSUE THREAD

**Issue by mauliknshah** [dsp-uga/Project-1-Naive-Bayes-classification#3]
The size of the document_term_matrix is about 13000 rows for the very small text corpus. For large documents it would be far large. On the other hand, document term matrix is very useful for calculating the naive-bayes model and it is desirable to have a copy of it on each node. What is the correct way to do it?

**Comment by raun1** [comment]
Hey, 
So currently my bottleneck is that i broadcasted the word + [occurrence in each class] and for every document the probabilities are getting calculated again and again. 
I was thinking once this iteration ends I would simply calculate that and save it to a text file/csv file and it can be loaded into memory and referenced in a udf.
Should solve my bottleneck issue.

**Comment by raun1** [comment]
But in answer to your question Nope its not that big of a problem for the large case. If you are broadcasting the doc term matrix. Basically how you access it is the issue.
